name: flutter_lint_rules_example
description: beauty box lint rules example.
version: 1.6.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  meta: ^1.3.0
  flutter_lint_rules:
    path: ../
