name: flutter_lint_rules

description: Lint rules for Dart and Flutter

version: 1.0.0

repository: "https://github.com/ziqq/flutter_lint_rules"

issue_tracker: "https://github.com/ziqq/flutter_lint_rules/issues"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_lints: ^4.0.0
